### ISSUE TITLE
how to use this audiovisualization with windows media player wmpdl

### ISSUE THREAD

**Issue by bas1c-codes** [VPKSoft/VPKSoft.AudioVisualization#2]
i need some help in your winforms nuget library  ( https://github.com/VPKSoft/VPKSoft.AudioVisualization )
I really like your package but I don’t know how to use it with winforms wmplib ( windows media player ) can you provide me some code and example to use your package in windows media player lib 

i couldn't understand your docs

**Comment by VPKSoft** [comment]
Hi,
Could you specify what documentation you don't understand? There is this about 100 lines of code demo application in the source:
![image](https://user-images.githubusercontent.com/40712699/157284238-e3769086-02e6-4255-8b8a-3fc83e2b795d.png)

The visualization component listens the current audio output, here is youtube in the background and the sample application visualizing the audio:
![image](https://user-images.githubusercontent.com/40712699/157284507-a5188b88-b676-4aa4-bb1a-1a16f46ccd12.png)

**Comment by bas1c-codes** [comment]
Hi i am sorry i know i am wasting your time i literally new to c# 

i made a music player using this tuto - https://www.youtube.com/watch?v=wjmU28ukjwA&t=1s

can you add this visualizer to this software and send the source code

**Comment by VPKSoft** [comment]
Hi,
It's great that you are learning C# and there is no bother to ask, but watching a 25 minutes of video to replicate the source code and update it to use the control would sort of be "out of range" from the hobby for me - sorry, but I have to respectfully decline from the "job".

Short image tutorial however, create a WinForms solution:
![image](https://user-images.githubusercontent.com/40712699/157476590-0458e033-483a-48ca-ae88-223a68836482.png)

Add the NuGet package for the solution:
![image](https://user-images.githubusercontent.com/40712699/157476640-cfa329cb-f0f4-4bec-8269-b7827c187d6d.png)

Install the NuGet package:
![image](https://user-images.githubusercontent.com/40712699/157476710-59be7f42-7f5e-4881-821f-c83fead1b54f.png)

Drop the package on the form (you can drop it to the music player you created):
![image](https://user-images.githubusercontent.com/40712699/157476913-402304bb-1194-47a6-b53f-82d69fdd34c4.png)

**Comment by bas1c-codes** [comment]
Hi its me again how can i remove the numbers

And 1 more question are a professional dev?

Does your company use winforms to make software (If not please say the lang and framework too)

**Comment by VPKSoft** [comment]
Hi,
The numbers can be removed by setting the _DisplayHertzLabels_ to _false_.
```cs
audioVisualizationBars1.DisplayHertzLabels = false;
```
Or in the designer:
![image](https://user-images.githubusercontent.com/40712699/160172426-bd9c566a-8825-4542-8301-7573395adc7d.png)

I work as a software developer. This VPKSoft is just me, not a company - a hobby. In the work we use C# with ASP.NET Core for the backend and Node.js, React and TypeScript for the frontend. SQL comes due the database for the software. Backend-frontend communication is done via RESTful calls.

For this hobby I have used quite much of WinForms with NET Core. Currently I'm trying to learn to use the Eto.Forms to replace WinForms as it is a cross-platform - not limited to Windows only.

**Comment by bas1c-codes** [comment]
Oh ok thanks for your visualizer its great winforms dont have any visualizer after a big search i found yours can i use it for commercial purpose.

Good Job!

**Comment by VPKSoft** [comment]
The visualizer is [MIT-licensed](https://en.wikipedia.org/wiki/MIT_License), so it can be used commercially or in proprietary software.
>The MIT License also permits reuse within [proprietary software](https://en.wikipedia.org/wiki/Proprietary_software), provided that all copies of the software or its substantial portions include a copy of the terms of the MIT License and also a copyright notice.

**Comment by bas1c-codes** [comment]
Hello sir

I have a doubt how did you used node.js in winforms?

**Comment by VPKSoft** [comment]
Hi,
It clearly reads: 
**At work:**
* C# with (ASP.)NET Core
* React with TypeScript and Node.js

**Hobby:**
* Mostly WinForms with NET Core

So in programming terms: `work != hobby` 🙂

**Comment by bas1c-codes** [comment]
OK
